//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloMobile4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hallinta
    {
        public int ID { get; set; }
        public string Huone { get; set; }
        public Nullable<int> Valot { get; set; }
        public Nullable<int> Lämpötila { get; set; }
        public Nullable<System.DateTime> Pvm { get; set; }
    }
}
